[package]
name = "hello-gl"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
anyhow = "1.0.62"
bytemuck = "1.12.1"
glutin = "0.29.1"

[build-dependencies]
gl_generator = "0.14.0"
